require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - Guardfile
Naming/MethodParameterName:
  Enabled: false
RSpec/ExampleLength:
  Max: 9
